# This file was generated by hand from the v0.1.0 release checksums.
# Future versions will be written by the GoReleaser workflow once the
# HOMEBREW_TAP_GITHUB_TOKEN secret lands on the source repo.
cask "t4p" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d924d89e9c6b0b08773b772f9635f808a2e2187b793f9d8c0ea5c08445fc813e"
      url "https://github.com/AleDeclerk/tokensforthepeople/releases/download/v#{version}/t4p_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da5c47a42d171e63c281ef723d87bdf493a97c71e1e8f8bf87baf815f1d0f6d7"
      url "https://github.com/AleDeclerk/tokensforthepeople/releases/download/v#{version}/t4p_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ef6e561989519f4a55adf12f2aa9a03b15c03bb61d5df9591abd9832a6402e3"
      url "https://github.com/AleDeclerk/tokensforthepeople/releases/download/v#{version}/t4p_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "452502b86deba46956646480264f47ae91ade13ec666559ce1a69edde02391f9"
      url "https://github.com/AleDeclerk/tokensforthepeople/releases/download/v#{version}/t4p_#{version}_linux_arm64.tar.gz"
    end
  end

  name "t4p"
  desc "Free LLM tokens for the rest of us — a Go wizard that wires Cline/Continue/Aider/LiteLLM to free tiers."
  homepage "https://github.com/AleDeclerk/tokensforthepeople"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t4p"
end
